export const linkTiles = {
  back: {
    linkPath: "../",
    text: "Back",
    icon: "/icons/chevron-back-circle-outline.svg",
    external: false,
  },
  gitHub: {
    linkPath: "https://github.com/kaBeech",
    text: "GitHub",
    icon: "/icons/logo-github.svg",
    external: false,
  },
  linkedIn: {
    linkPath: "https://www.linkedin.com/in/kyle-beechly/",
    text: "LinkedIn",
    icon: "/icons/logo-linkedin.svg",
    external: false,
  },
  email: {
    linkPath: "mailto:contact@kabeech.com",
    text: "Email Me!",
    icon: "/icons/mail.svg",
    external: true,
  },
  home: {
    linkPath: "/",
    text: "Home",
    icon: "/icons/home.svg",
    external: false,
  },
  fun: {
    linkPath: "/fun",
    text: "Fun",
    icon: "/icons/game-controller-outline.svg",
    external: false,
  },
  about: {
    linkPath: "/about-me",
    text: "About Me",
    icon: "/icons/person-circle-outline.svg",
    external: false,
  },
  tech: {
    linkPath: "/tech",
    text: "Tech",
    icon: "/icons/cpu.svg",
    external: false,
  },
  projects: {
    linkPath: "/projects",
    text: "Projects",
    icon: "/icons/hammer-outline.svg",
    external: false,
  },
  contact: {
    linkPath: "/contact",
    text: "Contact",
    icon: "/icons/mail.svg",
    external: false,
  },
  fun_buddhASketch: {
    linkPath: "https://kabeech.github.io/buddh-a-sketch/",
    text: "Buddh-A-Sketch",
    icon: "/icons/color-palette-outline.svg",
    external: true,
  },
  fun_flower: {
    linkPath: "/fun/flower?pride=true",
    text: "Flower",
    icon: "/icons/flower-outline.svg",
    external: false,
  },
  fun_ticTacToebot: {
    linkPath: "https://kabeech.github.io/tic-tac-toebot/",
    text: "Tic-Tac-Toebot",
    icon: "/icons/tic-tac-toebot-cropped-icon.svg",
    external: true,
  },
  projects_xtremeXmasCode: {
    linkPath: "https://www.xtremexmascode.com/",
    text: "Xtreme Xmas Code",
    icon: "/icons/tree.svg",
    external: true,
  },
  fun_alLughaMisma: {
    linkPath: "/fun/al-lugha-misma",
    text: "Al Lugha Misma",
    icon: "/icons/alLughaMismaLogo.webp",
    external: false,
  },
  fun_namagen: {
    linkPath: "/fun/namagen",
    text: "Namagen",
    icon: "/icons/peli_hype_mono.webp",
    external: false,
  },
  fun_starCrossed: {
    linkPath: "/fun/star-crossed",
    text: "StarCrossed",
    icon: "/icons/starCrossedIcon.webp",
    external: false,
  },
  flower_stereochrome: {
    linkPath: "./",
    text: "Stereochrome",
    icon: "/icons/apps-sharp.svg",
    external: false,
  },
  flower_rainbow: {
    linkPath: "?pride=true",
    text: "Rainbow",
    icon: "/icons/color-palette-outline.svg",
    external: false,
  },
  flower_romanesca: {
    linkPath: "?pride=true&romanesca=true",
    text: "Romanesca",
    icon: "/icons/cube-outline.svg",
    external: false,
  },
  flower_helix: {
    linkPath: "?pride=true&helix=true",
    text: "Helix",
    icon: "/icons/helix.svg",
    external: false,
  },
  alLughaMisma_legend: {
    linkPath: "/fun/al-lugha-misma/legend",
    text: "Al Lugha Misma Legend",
    icon: "/icons/alLughaMismaLogo.webp",
    external: false,
  },
  about_pronouns: {
    linkPath: "/about-me/pronouns",
    text: "Pronouns",
    icon: "/icons/transgender-outline.svg",
    external: false,
  },
  about_beechy: {
    linkPath: "/about-me/beechy",
    text: "Beechy",
    icon: "/icons/happy-outline.svg",
    external: false,
  },
  tech_poqd: {
    linkPath: "/tech/poqd",
    text: "POQD",
    icon: "/icons/server-outline.svg",
    external: false,
  },
  tech_edge: {
    linkPath: "/tech/edge",
    text: "Edge Functions",
    icon: "/icons/server.svg",
    external: false,
  },
  tech_wasm: {
    linkPath: "/tech/wasm",
    text: "WebAssembly",
    icon: "/icons/monitor.svg",
    external: false,
  },
  poqd_postgres: {
    linkPath: "https://www.postgresql.org/",
    text: "PostgreSQL",
    icon: "/icons/server-outline.svg",
    external: true,
  },
  poqd_oak: {
    linkPath: "https://oakserver.github.io/oak/",
    text: "Oak",
    icon: "/icons/server.svg",
    external: true,
  },
  poqd_qwik: {
    linkPath: "https://qwik.builder.io/",
    text: "Qwik",
    icon: "/icons/monitor.svg",
    external: true,
  },
  poqd_deno: {
    linkPath: "https://deno.land/",
    text: "Deno",
    icon: "/icons/hard-drive.svg",
    external: true,
  },
  projects_wyrldDashboard: {
    linkPath: "https://farreachco.com/",
    text: "Wyrld Dashboard",
    icon: "/icons/peli_hype_mono.webp",
    external: true,
  },
  projects_audiopile: {
    linkPath: "https://www.audiopile.cloud/",
    text: "Audiopile",
    icon: "/icons/musical-notes-outline.svg",
    external: true,
  },
  projects_tensort: {
    linkPath: "https://github.com/kaBeech/tensort",
    text: "Tensort",
    icon: "/icons/snow-outline.svg",
    external: true,
  },
  projects_guideMe: {
    linkPath: "https://gthub.com/kaBeech/guideme",
    text: "GuideMe",
    icon: "/icons/map-outline.svg",
    external: true,
  },
  projects_realDice: {
    linkPath: "https://github.com/kaBeech/real-dice",
    text: "Real* Dice*",
    icon: "/icons/real-dice.svg",
    external: true,
  },
};
