name: Deno Deploy

on:
  push:
    branches: [ "deploy-with-deno" ]
  pull_request:
    branches: [ "deploy-with-deno" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clean install
        run: npm ci

      - name: Build for deployment
        run: npm run build
        env: 
          STARCROSSED_API: ${{ secrets.STARCROSSED_API }}
          NAMAGEN_API: ${{ secrets.NAMAGEN_API }}
          AL_LUGHA_MISMA_API: ${{ secrets.AL_LUGHA_MISMA_API }}


      - name: Copy build artifacts
        run: mkdir app | cp -r node_modules app/node_modules | cp -r server app/server | cp -r dist app/dist

      - name: Change directory
        run: cd app/

      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh

      - name: Test
        run: /home/runner/.deno/bin/deno help

      - name: Install deployctl
        run: deno install --allow-all --no-check -r -f https://deno.land/x/deploy/deployctl.ts

      - name: Deploy to Deno Deploy
        run: deployctl deploy --project=${{ secrets.DENO_DEPLOY_PROJECT }} ./server/entry.deno.js
