name: Deno Deploy

on:
  push:
    branches: [ "deploy-with-deno" ]
  pull_request:
    branches: [ "deploy-with-deno" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: ls
        run: ls

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: empty-dove-51 # the name of the project on Deno Deploy
          entrypoint: ./app/server/entry.deno.js # the entrypoint to deploy
