name: Deno Deploymment

on:
  push:
    branches: [ "prod-deno" ]
  pull_request:
    branches: [ "prod-deno" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clean install
        run: npm ci

      - name: Build for deployment
        run: npm run build
        env: 
          STARCROSSED_API: ${{ secrets.STARCROSSED_API }}
          NAMAGEN_API: ${{ secrets.NAMAGEN_API }}
          AL_LUGHA_MISMA_API: ${{ secrets.AL_LUGHA_MISMA_API }}


      - name: Copy build artifacts
        run: mkdir app | cp -r node_modules app/node_modules | cp -r server app/server | cp -r dist app/dist

      - name: Change directory
        run: cd app/ | ls server/

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT }}
          entrypoint: ./server/entry.deno.js
