name: Docker Image Deno Build

on:
  push:
    branches: [ "prod-deno" ]
  pull_request:
    branches: [ "prod-deno" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.ECR_REPOSITORY }}:$(date +%s)
