name: Docker Image CI

on:
  push:
    branches: [ "deploy-with-deno" ]
  pull_request:
    branches: [ "deploy-with-deno" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kabeech-website:$(date +%s)

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up
